kestra-io/plugin-aws

- gradle.properties
- src/main/java/io/kestra/plugin/aws/s3/Download.java
- src/main/java/io/kestra/plugin/aws/s3/Downloads.java
- src/main/java/io/kestra/plugin/aws/s3/S3Service.java
- src/test/java/io/kestra/plugin/aws/s3/DownloadsTest.java
> fix: preserve file extension with the Download task

- src/main/java/io/kestra/plugin/aws/eventbridge/PutEvents.java
- src/test/java/io/kestra/plugin/aws/eventbridge/PutEventsTest.java
> chore: change input from internal storage to be ion

- build.gradle
- src/main/java/io/kestra/plugin/aws/kinesis/PutRecords.java
- src/main/java/io/kestra/plugin/aws/kinesis/model/Record.java
- src/main/java/io/kestra/plugin/aws/kinesis/package-info.java
- src/test/java/io/kestra/plugin/aws/kinesis/PutRecordsTest.java
> feat: add kinesis putrecord taks

- src/main/java/io/kestra/plugin/aws/ecr/GetAuthToken.java
- src/test/resources/application.yml
~Waiting for https://github.com/kestra-io/kestra/pull/3005~
> feat: encrypt the ECR auth token by default

- src/main/java/io/kestra/plugin/aws/sqs/Consume.java
Currently, we create thread that indefinitely wait for incoming message.
Also, each time you update your flow or trigger, I new thread is created. When some messages finally arrive, one random thread will get the data and set the trigger as success and start the new execution, however as it can be a thread from an old revision, it will trigger execution for previous revision of a flow.
close kestra-io/kestra#3533
> fix(consume): In Trigger, do not wait for incoming message

- src/main/java/io/kestra/plugin/aws/runner/AwsBatchTaskRunner.java
> feat(runner): properly handle TaskRunner kill (#442)

- src/main/java/io/kestra/plugin/aws/s3/Downloads.java
- src/test/java/io/kestra/plugin/aws/s3/DownloadsTest.java
> feat: Add 'outputFiles' property with a map of file name / URI

- src/main/java/io/kestra/plugin/aws/sqs/Consume.java
- src/main/java/io/kestra/plugin/aws/sqs/RealtimeTrigger.java
part-of: kestra-io/kestra#3767
> feat: enhance realtime trigger lifecycle

- src/main/java/io/kestra/plugin/aws/sqs/RealtimeTrigger.java
- src/main/java/io/kestra/plugin/aws/sqs/Trigger.java
Correct realtime trigger examples
Ensure there is a link/mention from Triggers to Realtime Triggers and vice versa
> fix(docs): correct aws sqs realtime trigger example

- build.gradle
- gradle.properties
> chore: use Kestra Platform BOM

- src/main/java/io/kestra/plugin/aws/sqs/Consume.java
- src/main/java/io/kestra/plugin/aws/sqs/RealtimeTrigger.java
> fix: add waitTimeSecods to SQS to avoid too many API calls

- src/main/java/io/kestra/plugin/aws/runner/Batch.java
> feat: resume AWS batch job

- src/main/java/io/kestra/plugin/aws/AbstractConnectionInterface.java
- src/main/resources/doc/io.kestra.plugin.aws.md
Fixes #347
@anna-geller you may want to have a look at those documentation improvements.
> feat: improve credential documentation

- src/main/java/io/kestra/plugin/aws/runner/Batch.java
> feat: download all files from the working directory in the task runner

- build.gradle
- src/main/java/io/kestra/plugin/aws/ConnectionUtils.java
- src/main/java/io/kestra/plugin/aws/sqs/AbstractSqs.java
- src/main/java/io/kestra/plugin/aws/sqs/RealtimeTrigger.java
fix: https://github.com/kestra-io/plugin-aws/issues/480
> fix(sqs): optimize async client and externalize config

- build.gradle
test containers #541 #539
localstack #540
bump software.amazon.awssdk.crt:aws-crt from 0.31.1 to 0.31.3 #538
> chore(deps): update dependencies

- src/main/java/io/kestra/plugin/aws/sqs/RealtimeTrigger.java
> fix(sqs): wait for receive message completion(#569)

- src/main/java/io/kestra/plugin/aws/athena/Query.java
- src/main/java/io/kestra/plugin/aws/auth/EksToken.java
- src/main/java/io/kestra/plugin/aws/cli/AwsCLI.java
- src/main/java/io/kestra/plugin/aws/dynamodb/DeleteItem.java
- src/main/java/io/kestra/plugin/aws/dynamodb/GetItem.java
- src/main/java/io/kestra/plugin/aws/dynamodb/PutItem.java
- src/main/java/io/kestra/plugin/aws/dynamodb/Query.java
- src/main/java/io/kestra/plugin/aws/dynamodb/Scan.java
- src/main/java/io/kestra/plugin/aws/ecr/GetAuthToken.java
- src/main/java/io/kestra/plugin/aws/emr/CreateClusterAndSubmitSteps.java
- src/main/java/io/kestra/plugin/aws/emr/DeleteCluster.java
- src/main/java/io/kestra/plugin/aws/eventbridge/PutEvents.java
- src/main/java/io/kestra/plugin/aws/glue/StartJobRun.java
- src/main/java/io/kestra/plugin/aws/kinesis/PutRecords.java
- src/main/java/io/kestra/plugin/aws/lambda/Invoke.java
- src/main/java/io/kestra/plugin/aws/s3/Copy.java
- src/main/java/io/kestra/plugin/aws/s3/Delete.java
- src/main/java/io/kestra/plugin/aws/s3/DeleteList.java
- src/main/java/io/kestra/plugin/aws/s3/Download.java
- src/main/java/io/kestra/plugin/aws/s3/Downloads.java
- src/main/java/io/kestra/plugin/aws/s3/List.java
- src/main/java/io/kestra/plugin/aws/s3/Trigger.java
- src/main/java/io/kestra/plugin/aws/sqs/Consume.java
- src/main/java/io/kestra/plugin/aws/sqs/Trigger.java
> Improve examples

- src/main/java/io/kestra/plugin/aws/s3/Trigger.java
- src/test/java/io/kestra/plugin/aws/s3/TriggerTest.java
- src/test/resources/flows/s3/s3-listen-localhost-force-path-style.yaml
> feat(s3): add forcePathStyle support to Trigger

- src/main/java/io/kestra/plugin/aws/cli/package-info.java
- src/main/java/io/kestra/plugin/aws/ecr/package-info.java
- src/main/java/io/kestra/plugin/aws/emr/package-info.java
- src/main/java/io/kestra/plugin/aws/sns/package-info.java
- src/main/java/io/kestra/plugin/aws/sqs/package-info.java
- part-of: https://github.com/kestra-io/kestra/issues/10631
> fix(): subgroups for better readability

- src/main/java/io/kestra/plugin/aws/sqs/Consume.java
- src/main/java/io/kestra/plugin/aws/sqs/RealtimeTrigger.java
- src/main/java/io/kestra/plugin/aws/sqs/Trigger.java
- src/test/java/io/kestra/plugin/aws/sqs/PublishThenConsumeTest.java
> feat(sqs): support to control autodelete
